pipeline:
  build:
    image: plugins/docker
    settings:
      repo: lblod/job-compression-service
      tags: latest
    secrets: [ docker_username, docker_password ]
when:
  branch: master
  event: push
